apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: b10e831c-dd98-4b6a-adcb-17118c92594d
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: 1c8e58fe-1e48-42b8-85b9-9aa266539dd0
          target-environment: QA-V2
