apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: fd1210a0-f36f-4622-9a59-4d090632cd77
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: fd1210a0-f36f-4622-9a59-4d090632cd77
          target-environment: QA-V2
