apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: e5fd69fc-46bd-4c9a-898e-a12b3734e2f4
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableRepo-QA
          artifact-id: 1c8e58fe-1e48-42b8-85b9-9aa266539dd0
          target-environment: QA-V2
